// Generated by CoffeeScript 1.3.3
var COMPLETE_UPDATE, DEQUEUE_UPDATE, QUEUE_VIEW, completeJob, db, dequeueJob, es, http, init, job, queueJob, request, status, view;

COMPLETE_UPDATE = "/_design/complete/_update/id/";

DEQUEUE_UPDATE = "/_design/dequeue/_update/id/";

QUEUE_VIEW = "/_design/queued/_view/name";

require('date-utils');

request = require('request');

http = require('http');

es = require('event-stream');

init = require(__dirname + '/init');

db = process.env.DB_URL || 'http://localhost:5984/cloudq';

module.exports = function(cb) {
  var start;
  start = function(cb) {
    return http.createServer(function(req, res) {
      var uri, _ref, _ref1;
      _ref = req.url.split('?'), uri = _ref[0], req.params = _ref[1];
      _ref1 = uri.split('/'), req.root = _ref1[0], req.queue = _ref1[1], req.queueId = _ref1[2];
      if (req.queue === '') {
        return status(res, 'Welcome to cloudq!');
      } else if (req.method === 'GET') {
        if (req.queue === 'api') {
          return view(req, res);
        } else {
          return dequeueJob(req, res);
        }
      } else if (req.method === 'POST') {
        return queueJob(req, res);
      } else if (req.method === 'DELETE') {
        return completeJob(req, res);
      } else {
        return status(res, 'Feature Not Implemented');
      }
    }).listen(process.env.PORT || process.env.VMC_APP_PORT || 3000, cb);
  };
  return init(db, function() {
    return start(cb);
  });
};

queueJob = function(req, res) {
  var jobify;
  jobify = function(data, cb) {
    var json, _ref;
    json = JSON.parse(data.toString());
    json.queue = req.queue;
    json.queue_state = 'queued';
    if ((_ref = json.priority) == null) {
      json.priority = 1;
    }
    json.expires_in = (new Date()).addDays(1);
    return cb(null, JSON.stringify(json));
  };
  return req.pipe(es.pipe(es.map(jobify), request.post(db, {
    json: true
  }))).pipe(res);
};

dequeueJob = function(req, res) {
  var view;
  view = QUEUE_VIEW + ("?key=%22" + req.queue + "%22&limit=1");
  return request(db + view, {
    json: true
  }, function(e, r, b) {
    var _ref, _ref1;
    if ((b != null ? (_ref = b.rows) != null ? (_ref1 = _ref[0]) != null ? _ref1.id : void 0 : void 0 : void 0) != null) {
      return request.put({
        uri: db + DEQUEUE_UPDATE + b.rows[0].id,
        json: true
      }, function(err) {
        if (err != null) {
          return status(res, err.message);
        }
        try {
          b.rows[0].value.job.id = b.rows[0].id;
          return job(res, b.rows[0].value.job);
        } catch (err) {
          return status(res, 'Job Node Not found.');
        }
      });
    } else {
      return status(res, 'empty');
    }
  });
};

completeJob = function(req, res) {
  return request.put({
    uri: db + COMPLETE_UPDATE + req.queueId,
    json: true
  }, function(err) {
    return status(res, 'complete');
  });
};

status = function(res, msg) {
  res.writeHead(200, {
    'content-type': 'application/json'
  });
  return res.end(JSON.stringify({
    status: msg
  }));
};

job = function(res, job) {
  res.writeHead(200, {
    'content-type': 'application/json'
  });
  return res.end(JSON.stringify(job));
};

view = function(req, res) {
  var name, uri;
  name = req.queueId;
  uri = "" + db + "/_design/" + name + "/_view/all?" + req.params;
  return request(uri, {
    json: true
  }).pipe(res);
};
