// Generated by CoffeeScript 1.3.3
var fs, pin, reload, request;

request = require('request');

fs = require('fs');

pin = require('linchpin');

module.exports = function(couchdb, cb) {
  request(couchdb, {
    json: true
  }, function(e, r, b) {
    if (b.error === 'not_found') {
      return pin.emit('COUCHDB:INIT:CREATEDB', couchdb);
    } else {
      return pin.emit('COUCHDB:INIT:VIEWS', couchdb);
    }
  });
  return pin.on('COUCHDB:INIT:DONE', cb);
};

pin.on('COUCHDB:INIT:CREATEDB', function(couchdb) {
  return request.put(couchdb, {
    json: true
  }, function(e, r, b) {
    console.log('Created Database: ' + couchdb);
    if (b.ok === true) {
      return pin.emit('COUCHDB:INIT:VIEWS', couchdb);
    }
  });
});

pin.on('COUCHDB:INIT:VIEWS', function(couchdb) {
  var count, done, res, view, views, _i, _len, _results;
  views = fs.readdirSync(__dirname + '/views');
  count = views.length;
  done = function(view) {
    console.log('Created View: ' + view);
    count = count - 1;
    if (count === 0) {
      return pin.emit('COUCHDB:INIT:DONE');
    }
  };
  res = function(view) {
    return done(view);
  };
  _results = [];
  for (_i = 0, _len = views.length; _i < _len; _i++) {
    view = views[_i];
    _results.push(reload(couchdb, view, res));
  }
  return _results;
});

reload = function(couchdb, view, cb) {
  var json, name;
  name = view.split('.')[0];
  json = fs.createReadStream(__dirname + '/views/' + view);
  return json.pipe(request.put(couchdb + '/_design/' + name, {
    json: true
  }, function() {
    return cb(name);
  }));
};
