// Generated by CoffeeScript 1.3.3
var broadway, queue;

broadway = require('broadway');

queue = new broadway.App();

queue.use(require(process.env.PLUGIN || './plugins/couchdb'));

queue.QUEUED = 'queued';

queue.RESERVED = 'reserved';

module.exports = queue;
